### ISSUE TITLE
During the build `flags` of undefined.

### ISSUE THREAD

**Issue by DeveloperFromUkraine** [angular/angular-bazel-example#294]
After start build at some point of compilation got next Error.

> Compiling Angular templates (ngc) //src:ngx-bootstrap failed (Exit 1)
: **TypeError: Cannot read property 'flags' of undefined**
    at checkUnreachable (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:29056:31)
    at bindChildrenWorker (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:27075:17)
    at bindChildren (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:27031:17)
    at bind (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:28309:21)
    at bindSourceFile (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:26645:17)
    at Object.bindSourceFile (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:26586:9)
    at initializeTypeChecker (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:56531:20)
    at Object.createTypeChecker (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:30810:9)
    at getDiagnosticsProducingTypeChecker (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:85089:93)
    at Object.getGlobalDiagnostics (/private/var/tmp/_bazel_vladimir/d5a999fbcbf03e52af06ead7f1d5a42c/execroot/ngx_bootstrap/bazel-out/host/bin/external/angular/@angular/bazel/ngc-wrapped.runfiles/npm/node_modules/typescript/lib/typescript.js:85480:53)

> Target //src:ngx-bootstrap failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 2,732s, Critical Path: 0,70s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully

**Comment by alexeagle** [comment]
looks like a version mismatch problem of the typescript npm package.
What version of typescript is installed in your project? are there any peer dependency warnings when you run npm/yarn to install?

**Comment by alexeagle** [comment]
Didn't hear back from you, I hope you resolved it by checking the TypeScript version.
